development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
  signature_expiration: 600
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
