---
:timeout: 60
:verbose: false
:pidfile: /tmp/sidekiq.pid
:concurrency: 145
:queues:
  - [critical, 100]
  - [opml,12]
  - [clients,11]
  - [users,10]
  - [subscriptions,9]
  - [comments,8]
  - [items,6]
  - [poll,5]
  - [icons,2]
:limits:
  opml: 10
  icons: 30
