---
:timeout: 60
:verbose: true
:pidfile: /tmp/sidekiq.pid
:concurrency: 50
:queues:
  - [critical, 9]
  - [clients,8]
  - [users,6]
  - [subscriptions,5]
  - [comments,4]
  - [items,3]
  - [process,2]
  - [icons,1]
